# Menu
menu:
  首页: /
  时间轴: /archives
  相册: /gallery
  分类: /categories
  标签: /tags
  关于: /about
rss: /atom.xml

# 语言
language: zh-CN

# Miscellaneous
favicon: /favicon.ico
brand: /images/logo.png

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/
  brand: /images/logo-white.png

# Content
excerpt_link: 阅读全文...

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: true # false
  clientID: 2e731d2b04096a7c71ab # GitHub Application Client ID
  clientSecret: 41e2e15eb8edebd8efd5a6da558a44d60f33468a # Client Secret
  repo: your # Repository name
  owner: liguoyou # GitHub ID
  admin: liguoyou # GitHub ID

# Valine
valine:
  enable: false # true
  el: "vcomments"
  appId:
  appKey:
  notify: false
  verify: true
  avatar: "mp"
  pageSize: "10"
  placeholder: "请输入..."