# Menu
menu:
  首页: /
  时间轴: /archives
  相册: /gallery
  关于: /about
rss: /atom.xml

# Miscellaneous
favicon: /bitbug_favicon.ico
brand: /images/logo.png

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: images/ocean/
  brand: /images/logo-white.png

# Content
excerpt_link: 阅读全文...

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: "vcomments"
  appId:
  appKey:
  notify: false
  verify: true
  avatar: "mp"
  pageSize: "10"
  placeholder: "请输入..."
